name: Lint & Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"

    - name: Install UV
      uses: astral-sh/setup-uv@v7

    - name: Install Python dependencies
      run: uv sync --dev

    - name: Build C extension
      run: uv run invoke build.all

    - name: Lint
      run: uv run invoke lint

    - name: Test
      run: uv run invoke test